/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SessionSessionInfo } from './sessionSessionInfo';
import { UserDto } from './userDto';

export interface AuthenticationAuthenticationResult { 
    user: UserDto;
    sessionInfo: SessionSessionInfo;
    accessToken: string;
    serverId: string;
}
