/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BaseItemPerson { 
    name?: string;
    id?: string;
    role?: string;
    type?: BaseItemPerson.TypeEnum;
    primaryImageTag?: string;
}
export namespace BaseItemPerson {
    export type TypeEnum = 'Actor' | 'Director' | 'Writer' | 'Producer' | 'GuestStar' | 'Composer' | 'Conductor' | 'Lyricist';
    export const TypeEnum = {
        Actor: 'Actor' as TypeEnum,
        Director: 'Director' as TypeEnum,
        Writer: 'Writer' as TypeEnum,
        Producer: 'Producer' as TypeEnum,
        GuestStar: 'GuestStar' as TypeEnum,
        Composer: 'Composer' as TypeEnum,
        Conductor: 'Conductor' as TypeEnum,
        Lyricist: 'Lyricist' as TypeEnum
    };
}