/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurationPathSubstitution } from './configurationPathSubstitution';

export interface ConfigurationServerConfiguration { 
    enableUPnP?: boolean;
    publicPort?: number;
    publicHttpsPort?: number;
    httpServerPortNumber?: number;
    httpsPortNumber?: number;
    enableHttps?: boolean;
    certificatePath?: string;
    certificatePassword?: string;
    isPortAuthorized?: boolean;
    autoRunWebApp?: boolean;
    enableRemoteAccess?: boolean;
    logAllQueryTimes?: boolean;
    enableCaseSensitiveItemIds?: boolean;
    metadataPath?: string;
    metadataNetworkPath?: string;
    preferredMetadataLanguage?: string;
    metadataCountryCode?: string;
    sortReplaceChars?: Array<string>;
    sortRemoveChars?: Array<string>;
    sortRemoveWords?: Array<string>;
    libraryMonitorDelay?: number;
    enableDashboardResponseCaching?: boolean;
    dashboardSourcePath?: string;
    imageSavingConvention?: ConfigurationServerConfiguration.ImageSavingConventionEnum;
    enableAutomaticRestart?: boolean;
    serverName?: string;
    wanDdns?: string;
    uICulture?: string;
    saveMetadataHidden?: boolean;
    remoteClientBitrateLimit?: number;
    displaySpecialsWithinSeasons?: boolean;
    localNetworkSubnets?: Array<string>;
    localNetworkAddresses?: Array<string>;
    enableExternalContentInSuggestions?: boolean;
    requireHttps?: boolean;
    isBehindProxy?: boolean;
    remoteIPFilter?: Array<string>;
    isRemoteIPFilterBlacklist?: boolean;
    imageExtractionTimeoutMs?: number;
    pathSubstitutions?: Array<ConfigurationPathSubstitution>;
    uninstalledPlugins?: Array<string>;
    collapseVideoFolders?: boolean;
    playlistsMigrated?: boolean;
    tagsMigrated?: boolean;
    enableOriginalTrackTitles?: boolean;
    vacuumDatabaseOnStartup?: boolean;
    libraryOptionsMigrated?: boolean;
    enableV2SortTitles?: boolean;
    simultaneousStreamLimit?: number;
    enableDebugLevelLogging?: boolean;
    enableAutoUpdate?: boolean;
    logFileRetentionDays?: number;
    runAtStartup?: boolean;
    isStartupWizardCompleted?: boolean;
    cachePath?: string;
}
export namespace ConfigurationServerConfiguration {
    export type ImageSavingConventionEnum = 'Legacy' | 'Compatible';
    export const ImageSavingConventionEnum = {
        Legacy: 'Legacy' as ImageSavingConventionEnum,
        Compatible: 'Compatible' as ImageSavingConventionEnum
    };
}