/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurationMediaPathInfo } from './configurationMediaPathInfo';
import { ConfigurationTypeOptions } from './configurationTypeOptions';

export interface ConfigurationLibraryOptions { 
    enableArchiveMediaFiles?: boolean;
    enablePhotos?: boolean;
    enableRealtimeMonitor?: boolean;
    enableChapterImageExtraction?: boolean;
    extractChapterImagesDuringLibraryScan?: boolean;
    downloadImagesInAdvance?: boolean;
    pathInfos?: Array<ConfigurationMediaPathInfo>;
    ignoreHiddenFiles?: boolean;
    ignoreFileExtensions?: Array<string>;
    saveLocalMetadata?: boolean;
    saveLocalThumbnailSets?: boolean;
    importMissingEpisodes?: boolean;
    enableAutomaticSeriesGrouping?: boolean;
    enableEmbeddedTitles?: boolean;
    enableAudioResume?: boolean;
    automaticRefreshIntervalDays?: number;
    preferredMetadataLanguage?: string;
    preferredImageLanguage?: string;
    contentType?: string;
    metadataCountryCode?: string;
    seasonZeroDisplayName?: string;
    name?: string;
    metadataSavers?: Array<string>;
    disabledLocalMetadataReaders?: Array<string>;
    localMetadataReaderOrder?: Array<string>;
    disabledSubtitleFetchers?: Array<string>;
    subtitleFetcherOrder?: Array<string>;
    skipSubtitlesIfEmbeddedSubtitlesPresent?: boolean;
    skipSubtitlesIfAudioTrackMatches?: boolean;
    subtitleDownloadLanguages?: Array<string>;
    requirePerfectSubtitleMatch?: boolean;
    saveSubtitlesWithMedia?: boolean;
    forcedSubtitlesOnly?: boolean;
    typeOptions?: Array<ConfigurationTypeOptions>;
    collapseSingleItemFolders?: boolean;
    minResumePct?: number;
    maxResumePct?: number;
    minResumeDurationSeconds?: number;
    thumbnailImagesIntervalSeconds?: number;
    sampleIgnoreSize?: number;
}