/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConfigurationAccessSchedule { 
    dayOfWeek?: ConfigurationAccessSchedule.DayOfWeekEnum;
    startHour?: number;
    endHour?: number;
}
export namespace ConfigurationAccessSchedule {
    export type DayOfWeekEnum = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Everyday' | 'Weekday' | 'Weekend';
    export const DayOfWeekEnum = {
        Sunday: 'Sunday' as DayOfWeekEnum,
        Monday: 'Monday' as DayOfWeekEnum,
        Tuesday: 'Tuesday' as DayOfWeekEnum,
        Wednesday: 'Wednesday' as DayOfWeekEnum,
        Thursday: 'Thursday' as DayOfWeekEnum,
        Friday: 'Friday' as DayOfWeekEnum,
        Saturday: 'Saturday' as DayOfWeekEnum,
        Everyday: 'Everyday' as DayOfWeekEnum,
        Weekday: 'Weekday' as DayOfWeekEnum,
        Weekend: 'Weekend' as DayOfWeekEnum
    };
}