/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DisplayPreferences { 
    id?: string;
    viewType?: string;
    sortBy?: string;
    indexBy?: string;
    rememberIndexing?: boolean;
    primaryImageHeight?: number;
    primaryImageWidth?: number;
    customPrefs?: { [key: string]: string; };
    scrollDirection?: DisplayPreferences.ScrollDirectionEnum;
    showBackdrop?: boolean;
    rememberSorting?: boolean;
    sortOrder?: DisplayPreferences.SortOrderEnum;
    showSidebar?: boolean;
    client?: string;
}
export namespace DisplayPreferences {
    export type ScrollDirectionEnum = 'Horizontal' | 'Vertical';
    export const ScrollDirectionEnum = {
        Horizontal: 'Horizontal' as ScrollDirectionEnum,
        Vertical: 'Vertical' as ScrollDirectionEnum
    };
    export type SortOrderEnum = 'Ascending' | 'Descending';
    export const SortOrderEnum = {
        Ascending: 'Ascending' as SortOrderEnum,
        Descending: 'Descending' as SortOrderEnum
    };
}