/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DlnaProfileCondition { 
    condition?: DlnaProfileCondition.ConditionEnum;
    property?: DlnaProfileCondition.PropertyEnum;
    value?: string;
    isRequired?: boolean;
}
export namespace DlnaProfileCondition {
    export type ConditionEnum = 'Equals' | 'NotEquals' | 'LessThanEqual' | 'GreaterThanEqual' | 'EqualsAny';
    export const ConditionEnum = {
        Equals: 'Equals' as ConditionEnum,
        NotEquals: 'NotEquals' as ConditionEnum,
        LessThanEqual: 'LessThanEqual' as ConditionEnum,
        GreaterThanEqual: 'GreaterThanEqual' as ConditionEnum,
        EqualsAny: 'EqualsAny' as ConditionEnum
    };
    export type PropertyEnum = 'AudioChannels' | 'AudioBitrate' | 'AudioProfile' | 'Width' | 'Height' | 'Has64BitOffsets' | 'PacketLength' | 'VideoBitDepth' | 'VideoBitrate' | 'VideoFramerate' | 'VideoLevel' | 'VideoProfile' | 'VideoTimestamp' | 'IsAnamorphic' | 'RefFrames' | 'NumAudioStreams' | 'NumVideoStreams' | 'IsSecondaryAudio' | 'VideoCodecTag' | 'IsAvc' | 'IsInterlaced' | 'AudioSampleRate' | 'AudioBitDepth';
    export const PropertyEnum = {
        AudioChannels: 'AudioChannels' as PropertyEnum,
        AudioBitrate: 'AudioBitrate' as PropertyEnum,
        AudioProfile: 'AudioProfile' as PropertyEnum,
        Width: 'Width' as PropertyEnum,
        Height: 'Height' as PropertyEnum,
        Has64BitOffsets: 'Has64BitOffsets' as PropertyEnum,
        PacketLength: 'PacketLength' as PropertyEnum,
        VideoBitDepth: 'VideoBitDepth' as PropertyEnum,
        VideoBitrate: 'VideoBitrate' as PropertyEnum,
        VideoFramerate: 'VideoFramerate' as PropertyEnum,
        VideoLevel: 'VideoLevel' as PropertyEnum,
        VideoProfile: 'VideoProfile' as PropertyEnum,
        VideoTimestamp: 'VideoTimestamp' as PropertyEnum,
        IsAnamorphic: 'IsAnamorphic' as PropertyEnum,
        RefFrames: 'RefFrames' as PropertyEnum,
        NumAudioStreams: 'NumAudioStreams' as PropertyEnum,
        NumVideoStreams: 'NumVideoStreams' as PropertyEnum,
        IsSecondaryAudio: 'IsSecondaryAudio' as PropertyEnum,
        VideoCodecTag: 'VideoCodecTag' as PropertyEnum,
        IsAvc: 'IsAvc' as PropertyEnum,
        IsInterlaced: 'IsInterlaced' as PropertyEnum,
        AudioSampleRate: 'AudioSampleRate' as PropertyEnum,
        AudioBitDepth: 'AudioBitDepth' as PropertyEnum
    };
}