/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DlnaDirectPlayProfile { 
    container?: string;
    audioCodec?: string;
    videoCodec?: string;
    type?: DlnaDirectPlayProfile.TypeEnum;
}
export namespace DlnaDirectPlayProfile {
    export type TypeEnum = 'Audio' | 'Video' | 'Photo';
    export const TypeEnum = {
        Audio: 'Audio' as TypeEnum,
        Video: 'Video' as TypeEnum,
        Photo: 'Photo' as TypeEnum
    };
}