/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DlnaDeviceProfileInfo { 
    id?: string;
    name?: string;
    type?: DlnaDeviceProfileInfo.TypeEnum;
}
export namespace DlnaDeviceProfileInfo {
    export type TypeEnum = 'System' | 'User';
    export const TypeEnum = {
        System: 'System' as TypeEnum,
        User: 'User' as TypeEnum
    };
}