/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DlnaTranscodingProfile { 
    container?: string;
    type?: DlnaTranscodingProfile.TypeEnum;
    videoCodec?: string;
    audioCodec?: string;
    protocol?: string;
    estimateContentLength?: boolean;
    enableMpegtsM2TsMode?: boolean;
    transcodeSeekInfo?: DlnaTranscodingProfile.TranscodeSeekInfoEnum;
    copyTimestamps?: boolean;
    context?: DlnaTranscodingProfile.ContextEnum;
    maxAudioChannels?: string;
    minSegments?: number;
    segmentLength?: number;
    breakOnNonKeyFrames?: boolean;
    manifestSubtitles?: string;
}
export namespace DlnaTranscodingProfile {
    export type TypeEnum = 'Audio' | 'Video' | 'Photo';
    export const TypeEnum = {
        Audio: 'Audio' as TypeEnum,
        Video: 'Video' as TypeEnum,
        Photo: 'Photo' as TypeEnum
    };
    export type TranscodeSeekInfoEnum = 'Auto' | 'Bytes';
    export const TranscodeSeekInfoEnum = {
        Auto: 'Auto' as TranscodeSeekInfoEnum,
        Bytes: 'Bytes' as TranscodeSeekInfoEnum
    };
    export type ContextEnum = 'Streaming' | 'Static';
    export const ContextEnum = {
        Streaming: 'Streaming' as ContextEnum,
        Static: 'Static' as ContextEnum
    };
}