/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DlnaHttpHeaderInfo } from './dlnaHttpHeaderInfo';

export interface DlnaDeviceIdentification { 
    friendlyName?: string;
    modelNumber?: string;
    serialNumber?: string;
    modelName?: string;
    modelDescription?: string;
    deviceDescription?: string;
    modelUrl?: string;
    manufacturer?: string;
    manufacturerUrl?: string;
    headers?: Array<DlnaHttpHeaderInfo>;
}