/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DlnaSubtitleProfile { 
    format?: string;
    method?: DlnaSubtitleProfile.MethodEnum;
    didlMode?: string;
    language?: string;
    container?: string;
}
export namespace DlnaSubtitleProfile {
    export type MethodEnum = 'Encode' | 'Embed' | 'External' | 'Hls';
    export const MethodEnum = {
        Encode: 'Encode' as MethodEnum,
        Embed: 'Embed' as MethodEnum,
        External: 'External' as MethodEnum,
        Hls: 'Hls' as MethodEnum
    };
}