/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmbyNotificationsApiNotification { 
    id?: string;
    userId?: string;
    date?: Date;
    isRead?: boolean;
    name?: string;
    description?: string;
    url?: string;
    level?: EmbyNotificationsApiNotification.LevelEnum;
}
export namespace EmbyNotificationsApiNotification {
    export type LevelEnum = 'Normal' | 'Warning' | 'Error';
    export const LevelEnum = {
        Normal: 'Normal' as LevelEnum,
        Warning: 'Warning' as LevelEnum,
        Error: 'Error' as LevelEnum
    };
}