/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmbyReportsApiModelReportItem } from './embyReportsApiModelReportItem';

export interface EmbyReportsApiModelReportRow { 
    id?: string;
    hasImageTagsBackdrop?: boolean;
    hasImageTagsPrimary?: boolean;
    hasImageTagsLogo?: boolean;
    hasLocalTrailer?: boolean;
    hasLockData?: boolean;
    hasEmbeddedImage?: boolean;
    hasSubtitles?: boolean;
    hasSpecials?: boolean;
    columns?: Array<EmbyReportsApiModelReportItem>;
    rowType?: EmbyReportsApiModelReportRow.RowTypeEnum;
    userId?: string;
}
export namespace EmbyReportsApiModelReportRow {
    export type RowTypeEnum = 'MusicArtist' | 'MusicAlbum' | 'Book' | 'BoxSet' | 'Episode' | 'Game' | 'Video' | 'Movie' | 'MusicVideo' | 'Trailer' | 'Season' | 'Series' | 'Audio' | 'BaseItem' | 'Artist';
    export const RowTypeEnum = {
        MusicArtist: 'MusicArtist' as RowTypeEnum,
        MusicAlbum: 'MusicAlbum' as RowTypeEnum,
        Book: 'Book' as RowTypeEnum,
        BoxSet: 'BoxSet' as RowTypeEnum,
        Episode: 'Episode' as RowTypeEnum,
        Game: 'Game' as RowTypeEnum,
        Video: 'Video' as RowTypeEnum,
        Movie: 'Movie' as RowTypeEnum,
        MusicVideo: 'MusicVideo' as RowTypeEnum,
        Trailer: 'Trailer' as RowTypeEnum,
        Season: 'Season' as RowTypeEnum,
        Series: 'Series' as RowTypeEnum,
        Audio: 'Audio' as RowTypeEnum,
        BaseItem: 'BaseItem' as RowTypeEnum,
        Artist: 'Artist' as RowTypeEnum
    };
}