/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmbyReportsApiModelReportHeader { 
    headerFieldType?: EmbyReportsApiModelReportHeader.HeaderFieldTypeEnum;
    name?: string;
    fieldName?: EmbyReportsApiModelReportHeader.FieldNameEnum;
    sortField?: string;
    type?: string;
    itemViewType?: EmbyReportsApiModelReportHeader.ItemViewTypeEnum;
    visible?: boolean;
    displayType?: EmbyReportsApiModelReportHeader.DisplayTypeEnum;
    showHeaderLabel?: boolean;
    canGroup?: boolean;
}
export namespace EmbyReportsApiModelReportHeader {
    export type HeaderFieldTypeEnum = 'String' | 'Boolean' | 'Date' | 'Time' | 'DateTime' | 'Int' | 'Image' | 'Object' | 'Minutes';
    export const HeaderFieldTypeEnum = {
        String: 'String' as HeaderFieldTypeEnum,
        Boolean: 'Boolean' as HeaderFieldTypeEnum,
        Date: 'Date' as HeaderFieldTypeEnum,
        Time: 'Time' as HeaderFieldTypeEnum,
        DateTime: 'DateTime' as HeaderFieldTypeEnum,
        Int: 'Int' as HeaderFieldTypeEnum,
        Image: 'Image' as HeaderFieldTypeEnum,
        Object: 'Object' as HeaderFieldTypeEnum,
        Minutes: 'Minutes' as HeaderFieldTypeEnum
    };
    export type FieldNameEnum = 'None' | 'Path' | 'Name' | 'PremiereDate' | 'DateAdded' | 'ReleaseDate' | 'Runtime' | 'PlayCount' | 'Season' | 'SeasonNumber' | 'Series' | 'Network' | 'Year' | 'ParentalRating' | 'CommunityRating' | 'Trailers' | 'Specials' | 'GameSystem' | 'AlbumArtist' | 'Album' | 'Disc' | 'Track' | 'Audio' | 'EmbeddedImage' | 'Video' | 'Resolution' | 'Subtitles' | 'Genres' | 'Countries' | 'Status' | 'Tracks' | 'EpisodeSeries' | 'EpisodeSeason' | 'EpisodeNumber' | 'AudioAlbumArtist' | 'MusicArtist' | 'AudioAlbum' | 'Locked' | 'ImagePrimary' | 'ImageBackdrop' | 'ImageLogo' | 'Actor' | 'Studios' | 'Composer' | 'Director' | 'GuestStar' | 'Producer' | 'Writer' | 'Artist' | 'Years' | 'ParentalRatings' | 'CommunityRatings' | 'Overview' | 'ShortOverview' | 'Type' | 'Date' | 'UserPrimaryImage' | 'Severity' | 'Item' | 'User' | 'UserId';
    export const FieldNameEnum = {
        None: 'None' as FieldNameEnum,
        Path: 'Path' as FieldNameEnum,
        Name: 'Name' as FieldNameEnum,
        PremiereDate: 'PremiereDate' as FieldNameEnum,
        DateAdded: 'DateAdded' as FieldNameEnum,
        ReleaseDate: 'ReleaseDate' as FieldNameEnum,
        Runtime: 'Runtime' as FieldNameEnum,
        PlayCount: 'PlayCount' as FieldNameEnum,
        Season: 'Season' as FieldNameEnum,
        SeasonNumber: 'SeasonNumber' as FieldNameEnum,
        Series: 'Series' as FieldNameEnum,
        Network: 'Network' as FieldNameEnum,
        Year: 'Year' as FieldNameEnum,
        ParentalRating: 'ParentalRating' as FieldNameEnum,
        CommunityRating: 'CommunityRating' as FieldNameEnum,
        Trailers: 'Trailers' as FieldNameEnum,
        Specials: 'Specials' as FieldNameEnum,
        GameSystem: 'GameSystem' as FieldNameEnum,
        AlbumArtist: 'AlbumArtist' as FieldNameEnum,
        Album: 'Album' as FieldNameEnum,
        Disc: 'Disc' as FieldNameEnum,
        Track: 'Track' as FieldNameEnum,
        Audio: 'Audio' as FieldNameEnum,
        EmbeddedImage: 'EmbeddedImage' as FieldNameEnum,
        Video: 'Video' as FieldNameEnum,
        Resolution: 'Resolution' as FieldNameEnum,
        Subtitles: 'Subtitles' as FieldNameEnum,
        Genres: 'Genres' as FieldNameEnum,
        Countries: 'Countries' as FieldNameEnum,
        Status: 'Status' as FieldNameEnum,
        Tracks: 'Tracks' as FieldNameEnum,
        EpisodeSeries: 'EpisodeSeries' as FieldNameEnum,
        EpisodeSeason: 'EpisodeSeason' as FieldNameEnum,
        EpisodeNumber: 'EpisodeNumber' as FieldNameEnum,
        AudioAlbumArtist: 'AudioAlbumArtist' as FieldNameEnum,
        MusicArtist: 'MusicArtist' as FieldNameEnum,
        AudioAlbum: 'AudioAlbum' as FieldNameEnum,
        Locked: 'Locked' as FieldNameEnum,
        ImagePrimary: 'ImagePrimary' as FieldNameEnum,
        ImageBackdrop: 'ImageBackdrop' as FieldNameEnum,
        ImageLogo: 'ImageLogo' as FieldNameEnum,
        Actor: 'Actor' as FieldNameEnum,
        Studios: 'Studios' as FieldNameEnum,
        Composer: 'Composer' as FieldNameEnum,
        Director: 'Director' as FieldNameEnum,
        GuestStar: 'GuestStar' as FieldNameEnum,
        Producer: 'Producer' as FieldNameEnum,
        Writer: 'Writer' as FieldNameEnum,
        Artist: 'Artist' as FieldNameEnum,
        Years: 'Years' as FieldNameEnum,
        ParentalRatings: 'ParentalRatings' as FieldNameEnum,
        CommunityRatings: 'CommunityRatings' as FieldNameEnum,
        Overview: 'Overview' as FieldNameEnum,
        ShortOverview: 'ShortOverview' as FieldNameEnum,
        Type: 'Type' as FieldNameEnum,
        Date: 'Date' as FieldNameEnum,
        UserPrimaryImage: 'UserPrimaryImage' as FieldNameEnum,
        Severity: 'Severity' as FieldNameEnum,
        Item: 'Item' as FieldNameEnum,
        User: 'User' as FieldNameEnum,
        UserId: 'UserId' as FieldNameEnum
    };
    export type ItemViewTypeEnum = 'None' | 'Detail' | 'Edit' | 'List' | 'ItemByNameDetails' | 'StatusImage' | 'EmbeddedImage' | 'SubtitleImage' | 'TrailersImage' | 'SpecialsImage' | 'LockDataImage' | 'TagsPrimaryImage' | 'TagsBackdropImage' | 'TagsLogoImage' | 'UserPrimaryImage';
    export const ItemViewTypeEnum = {
        None: 'None' as ItemViewTypeEnum,
        Detail: 'Detail' as ItemViewTypeEnum,
        Edit: 'Edit' as ItemViewTypeEnum,
        List: 'List' as ItemViewTypeEnum,
        ItemByNameDetails: 'ItemByNameDetails' as ItemViewTypeEnum,
        StatusImage: 'StatusImage' as ItemViewTypeEnum,
        EmbeddedImage: 'EmbeddedImage' as ItemViewTypeEnum,
        SubtitleImage: 'SubtitleImage' as ItemViewTypeEnum,
        TrailersImage: 'TrailersImage' as ItemViewTypeEnum,
        SpecialsImage: 'SpecialsImage' as ItemViewTypeEnum,
        LockDataImage: 'LockDataImage' as ItemViewTypeEnum,
        TagsPrimaryImage: 'TagsPrimaryImage' as ItemViewTypeEnum,
        TagsBackdropImage: 'TagsBackdropImage' as ItemViewTypeEnum,
        TagsLogoImage: 'TagsLogoImage' as ItemViewTypeEnum,
        UserPrimaryImage: 'UserPrimaryImage' as ItemViewTypeEnum
    };
    export type DisplayTypeEnum = 'None' | 'Screen' | 'Export' | 'ScreenExport';
    export const DisplayTypeEnum = {
        None: 'None' as DisplayTypeEnum,
        Screen: 'Screen' as DisplayTypeEnum,
        Export: 'Export' as DisplayTypeEnum,
        ScreenExport: 'ScreenExport' as DisplayTypeEnum
    };
}