/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmbyMediaModelTypesBitRate } from './embyMediaModelTypesBitRate';
import { EmbyMediaModelTypesResolutionWithRate } from './embyMediaModelTypesResolutionWithRate';

export interface EmbyMediaModelTypesLevelInformation { 
    shortName?: string;
    description?: string;
    ordinal?: number;
    maxBitRate?: EmbyMediaModelTypesBitRate;
    maxBitRateDisplay?: string;
    id?: string;
    resolutionRates?: Array<EmbyMediaModelTypesResolutionWithRate>;
    resolutionRateStrings?: Array<string>;
    resolutionRatesDisplay?: string;
}