/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ImageInfo { 
    imageType?: ImageInfo.ImageTypeEnum;
    imageIndex?: number;
    path?: string;
    height?: number;
    width?: number;
    size?: number;
}
export namespace ImageInfo {
    export type ImageTypeEnum = 'Primary' | 'Art' | 'Backdrop' | 'Banner' | 'Logo' | 'Thumb' | 'Disc' | 'Box' | 'Screenshot' | 'Menu' | 'Chapter' | 'BoxRear' | 'Thumbnail';
    export const ImageTypeEnum = {
        Primary: 'Primary' as ImageTypeEnum,
        Art: 'Art' as ImageTypeEnum,
        Backdrop: 'Backdrop' as ImageTypeEnum,
        Banner: 'Banner' as ImageTypeEnum,
        Logo: 'Logo' as ImageTypeEnum,
        Thumb: 'Thumb' as ImageTypeEnum,
        Disc: 'Disc' as ImageTypeEnum,
        Box: 'Box' as ImageTypeEnum,
        Screenshot: 'Screenshot' as ImageTypeEnum,
        Menu: 'Menu' as ImageTypeEnum,
        Chapter: 'Chapter' as ImageTypeEnum,
        BoxRear: 'BoxRear' as ImageTypeEnum,
        Thumbnail: 'Thumbnail' as ImageTypeEnum
    };
}