/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ImageProviderInfo { 
    name?: string;
    supportedImages?: Array<ImageProviderInfo.SupportedImagesEnum>;
}
export namespace ImageProviderInfo {
    export type SupportedImagesEnum = 'Primary' | 'Art' | 'Backdrop' | 'Banner' | 'Logo' | 'Thumb' | 'Disc' | 'Box' | 'Screenshot' | 'Menu' | 'Chapter' | 'BoxRear' | 'Thumbnail';
    export const SupportedImagesEnum = {
        Primary: 'Primary' as SupportedImagesEnum,
        Art: 'Art' as SupportedImagesEnum,
        Backdrop: 'Backdrop' as SupportedImagesEnum,
        Banner: 'Banner' as SupportedImagesEnum,
        Logo: 'Logo' as SupportedImagesEnum,
        Thumb: 'Thumb' as SupportedImagesEnum,
        Disc: 'Disc' as SupportedImagesEnum,
        Box: 'Box' as SupportedImagesEnum,
        Screenshot: 'Screenshot' as SupportedImagesEnum,
        Menu: 'Menu' as SupportedImagesEnum,
        Chapter: 'Chapter' as SupportedImagesEnum,
        BoxRear: 'BoxRear' as SupportedImagesEnum,
        Thumbnail: 'Thumbnail' as SupportedImagesEnum
    };
}