/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IOFileSystemEntryInfo { 
    name?: string;
    path?: string;
    type?: IOFileSystemEntryInfo.TypeEnum;
}
export namespace IOFileSystemEntryInfo {
    export type TypeEnum = 'File' | 'Directory' | 'NetworkComputer' | 'NetworkShare';
    export const TypeEnum = {
        File: 'File' as TypeEnum,
        Directory: 'Directory' as TypeEnum,
        NetworkComputer: 'NetworkComputer' as TypeEnum,
        NetworkShare: 'NetworkShare' as TypeEnum
    };
}