/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ItemCounts { 
    movieCount?: number;
    seriesCount?: number;
    episodeCount?: number;
    gameCount?: number;
    artistCount?: number;
    programCount?: number;
    gameSystemCount?: number;
    trailerCount?: number;
    songCount?: number;
    albumCount?: number;
    musicVideoCount?: number;
    boxSetCount?: number;
    bookCount?: number;
    itemCount?: number;
}