/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurationImageOption } from './configurationImageOption';
import { LibraryLibraryOptionInfo } from './libraryLibraryOptionInfo';

export interface LibraryLibraryTypeOptions { 
    type?: string;
    metadataFetchers?: Array<LibraryLibraryOptionInfo>;
    imageFetchers?: Array<LibraryLibraryOptionInfo>;
    supportedImageTypes?: Array<LibraryLibraryTypeOptions.SupportedImageTypesEnum>;
    defaultImageOptions?: Array<ConfigurationImageOption>;
}
export namespace LibraryLibraryTypeOptions {
    export type SupportedImageTypesEnum = 'Primary' | 'Art' | 'Backdrop' | 'Banner' | 'Logo' | 'Thumb' | 'Disc' | 'Box' | 'Screenshot' | 'Menu' | 'Chapter' | 'BoxRear' | 'Thumbnail';
    export const SupportedImageTypesEnum = {
        Primary: 'Primary' as SupportedImageTypesEnum,
        Art: 'Art' as SupportedImageTypesEnum,
        Backdrop: 'Backdrop' as SupportedImageTypesEnum,
        Banner: 'Banner' as SupportedImageTypesEnum,
        Logo: 'Logo' as SupportedImageTypesEnum,
        Thumb: 'Thumb' as SupportedImageTypesEnum,
        Disc: 'Disc' as SupportedImageTypesEnum,
        Box: 'Box' as SupportedImageTypesEnum,
        Screenshot: 'Screenshot' as SupportedImageTypesEnum,
        Menu: 'Menu' as SupportedImageTypesEnum,
        Chapter: 'Chapter' as SupportedImageTypesEnum,
        BoxRear: 'BoxRear' as SupportedImageTypesEnum,
        Thumbnail: 'Thumbnail' as SupportedImageTypesEnum
    };
}