/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NameValuePair } from './nameValuePair';

export interface LiveTvListingsProviderInfo { 
    name?: string;
    setupUrl?: string;
    id?: string;
    type?: string;
    username?: string;
    password?: string;
    listingsId?: string;
    zipCode?: string;
    country?: string;
    path?: string;
    enabledTuners?: Array<string>;
    enableAllTuners?: boolean;
    newsCategories?: Array<string>;
    sportsCategories?: Array<string>;
    kidsCategories?: Array<string>;
    movieCategories?: Array<string>;
    channelMappings?: Array<NameValuePair>;
    moviePrefix?: string;
    preferredLanguage?: string;
    userAgent?: string;
}