/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LiveTvSeriesTimerInfoDto { 
    recordAnyTime?: boolean;
    skipEpisodesInLibrary?: boolean;
    recordAnyChannel?: boolean;
    keepUpTo?: number;
    recordNewOnly?: boolean;
    days?: Array<LiveTvSeriesTimerInfoDto.DaysEnum>;
    dayPattern?: LiveTvSeriesTimerInfoDto.DayPatternEnum;
    imageTags?: { [key: string]: string; };
    parentThumbItemId?: string;
    parentThumbImageTag?: string;
    parentPrimaryImageItemId?: string;
    parentPrimaryImageTag?: string;
    id?: string;
    type?: string;
    serverId?: string;
    externalId?: string;
    channelId?: string;
    externalChannelId?: string;
    channelName?: string;
    channelPrimaryImageTag?: string;
    programId?: string;
    externalProgramId?: string;
    name?: string;
    overview?: string;
    startDate?: Date;
    endDate?: Date;
    serviceName?: string;
    priority?: number;
    prePaddingSeconds?: number;
    postPaddingSeconds?: number;
    isPrePaddingRequired?: boolean;
    parentBackdropItemId?: string;
    parentBackdropImageTags?: Array<string>;
    isPostPaddingRequired?: boolean;
    keepUntil?: LiveTvSeriesTimerInfoDto.KeepUntilEnum;
}
export namespace LiveTvSeriesTimerInfoDto {
    export type DaysEnum = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';
    export const DaysEnum = {
        Sunday: 'Sunday' as DaysEnum,
        Monday: 'Monday' as DaysEnum,
        Tuesday: 'Tuesday' as DaysEnum,
        Wednesday: 'Wednesday' as DaysEnum,
        Thursday: 'Thursday' as DaysEnum,
        Friday: 'Friday' as DaysEnum,
        Saturday: 'Saturday' as DaysEnum
    };
    export type DayPatternEnum = 'Daily' | 'Weekdays' | 'Weekends';
    export const DayPatternEnum = {
        Daily: 'Daily' as DayPatternEnum,
        Weekdays: 'Weekdays' as DayPatternEnum,
        Weekends: 'Weekends' as DayPatternEnum
    };
    export type KeepUntilEnum = 'UntilDeleted' | 'UntilSpaceNeeded' | 'UntilWatched' | 'UntilDate';
    export const KeepUntilEnum = {
        UntilDeleted: 'UntilDeleted' as KeepUntilEnum,
        UntilSpaceNeeded: 'UntilSpaceNeeded' as KeepUntilEnum,
        UntilWatched: 'UntilWatched' as KeepUntilEnum,
        UntilDate: 'UntilDate' as KeepUntilEnum
    };
}