/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LiveTvLiveTvServiceInfo } from './liveTvLiveTvServiceInfo';

export interface LiveTvLiveTvInfo { 
    services?: Array<LiveTvLiveTvServiceInfo>;
    isEnabled?: boolean;
    enabledUsers?: Array<string>;
}