/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LiveTvLiveTvServiceInfo { 
    name?: string;
    homePageUrl?: string;
    status?: LiveTvLiveTvServiceInfo.StatusEnum;
    statusMessage?: string;
    version?: string;
    hasUpdateAvailable?: boolean;
    isVisible?: boolean;
    tuners?: Array<string>;
}
export namespace LiveTvLiveTvServiceInfo {
    export type StatusEnum = 'Ok' | 'Unavailable';
    export const StatusEnum = {
        Ok: 'Ok' as StatusEnum,
        Unavailable: 'Unavailable' as StatusEnum
    };
}