/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseItemDto } from './baseItemDto';

export interface LiveTvTimerInfoDto { 
    status?: LiveTvTimerInfoDto.StatusEnum;
    seriesTimerId?: string;
    externalSeriesTimerId?: string;
    runTimeTicks?: number;
    programInfo?: BaseItemDto;
    id?: string;
    type?: string;
    serverId?: string;
    externalId?: string;
    channelId?: string;
    externalChannelId?: string;
    channelName?: string;
    channelPrimaryImageTag?: string;
    programId?: string;
    externalProgramId?: string;
    name?: string;
    overview?: string;
    startDate?: Date;
    endDate?: Date;
    serviceName?: string;
    priority?: number;
    prePaddingSeconds?: number;
    postPaddingSeconds?: number;
    isPrePaddingRequired?: boolean;
    parentBackdropItemId?: string;
    parentBackdropImageTags?: Array<string>;
    isPostPaddingRequired?: boolean;
    keepUntil?: LiveTvTimerInfoDto.KeepUntilEnum;
}
export namespace LiveTvTimerInfoDto {
    export type StatusEnum = 'New' | 'InProgress' | 'Completed' | 'Cancelled' | 'ConflictedOk' | 'ConflictedNotOk' | 'Error';
    export const StatusEnum = {
        New: 'New' as StatusEnum,
        InProgress: 'InProgress' as StatusEnum,
        Completed: 'Completed' as StatusEnum,
        Cancelled: 'Cancelled' as StatusEnum,
        ConflictedOk: 'ConflictedOk' as StatusEnum,
        ConflictedNotOk: 'ConflictedNotOk' as StatusEnum,
        Error: 'Error' as StatusEnum
    };
    export type KeepUntilEnum = 'UntilDeleted' | 'UntilSpaceNeeded' | 'UntilWatched' | 'UntilDate';
    export const KeepUntilEnum = {
        UntilDeleted: 'UntilDeleted' as KeepUntilEnum,
        UntilSpaceNeeded: 'UntilSpaceNeeded' as KeepUntilEnum,
        UntilWatched: 'UntilWatched' as KeepUntilEnum,
        UntilDate: 'UntilDate' as KeepUntilEnum
    };
}