/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DlnaDeviceProfile } from './dlnaDeviceProfile';

export interface MediaInfoPlaybackInfoRequest { 
    id?: string;
    userId?: string;
    maxStreamingBitrate?: number;
    startTimeTicks?: number;
    audioStreamIndex?: number;
    subtitleStreamIndex?: number;
    maxAudioChannels?: number;
    mediaSourceId?: string;
    liveStreamId?: string;
    deviceProfile?: DlnaDeviceProfile;
    enableDirectPlay?: boolean;
    enableDirectStream?: boolean;
    enableTranscoding?: boolean;
    allowVideoStreamCopy?: boolean;
    allowAudioStreamCopy?: boolean;
    isPlayback?: boolean;
    autoOpenLiveStream?: boolean;
    directPlayProtocols?: Array<MediaInfoPlaybackInfoRequest.DirectPlayProtocolsEnum>;
    currentPlaySessionId?: string;
}
export namespace MediaInfoPlaybackInfoRequest {
    export type DirectPlayProtocolsEnum = 'File' | 'Http' | 'Rtmp' | 'Rtsp' | 'Udp' | 'Rtp' | 'Ftp' | 'Mms';
    export const DirectPlayProtocolsEnum = {
        File: 'File' as DirectPlayProtocolsEnum,
        Http: 'Http' as DirectPlayProtocolsEnum,
        Rtmp: 'Rtmp' as DirectPlayProtocolsEnum,
        Rtsp: 'Rtsp' as DirectPlayProtocolsEnum,
        Udp: 'Udp' as DirectPlayProtocolsEnum,
        Rtp: 'Rtp' as DirectPlayProtocolsEnum,
        Ftp: 'Ftp' as DirectPlayProtocolsEnum,
        Mms: 'Mms' as DirectPlayProtocolsEnum
    };
}