/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MediaEncodingApiOnPlaybackProgress { 
    playlistIndex?: number;
    playlistLength?: number;
    eventName?: MediaEncodingApiOnPlaybackProgress.EventNameEnum;
}
export namespace MediaEncodingApiOnPlaybackProgress {
    export type EventNameEnum = 'TimeUpdate' | 'Pause' | 'Unpause' | 'VolumeChange' | 'RepeatModeChange' | 'AudioTrackChange' | 'SubtitleTrackChange' | 'PlaylistItemMove' | 'PlaylistItemRemove' | 'PlaylistItemAdd' | 'QualityChange' | 'StateChange';
    export const EventNameEnum = {
        TimeUpdate: 'TimeUpdate' as EventNameEnum,
        Pause: 'Pause' as EventNameEnum,
        Unpause: 'Unpause' as EventNameEnum,
        VolumeChange: 'VolumeChange' as EventNameEnum,
        RepeatModeChange: 'RepeatModeChange' as EventNameEnum,
        AudioTrackChange: 'AudioTrackChange' as EventNameEnum,
        SubtitleTrackChange: 'SubtitleTrackChange' as EventNameEnum,
        PlaylistItemMove: 'PlaylistItemMove' as EventNameEnum,
        PlaylistItemRemove: 'PlaylistItemRemove' as EventNameEnum,
        PlaylistItemAdd: 'PlaylistItemAdd' as EventNameEnum,
        QualityChange: 'QualityChange' as EventNameEnum,
        StateChange: 'StateChange' as EventNameEnum
    };
}