/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseItemDto } from './baseItemDto';
import { QueueItem } from './queueItem';

export interface PlaybackStopInfo { 
    nowPlayingQueue?: Array<QueueItem>;
    playlistItemId?: string;
    playlistIndex?: number;
    playlistLength?: number;
    item?: BaseItemDto;
    itemId?: string;
    sessionId?: string;
    mediaSourceId?: string;
    positionTicks?: number;
    liveStreamId?: string;
    playSessionId?: string;
    failed?: boolean;
    nextMediaType?: string;
}