/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PlayerStateInfo { 
    positionTicks?: number;
    canSeek?: boolean;
    isPaused?: boolean;
    isMuted?: boolean;
    volumeLevel?: number;
    audioStreamIndex?: number;
    subtitleStreamIndex?: number;
    mediaSourceId?: string;
    playMethod?: PlayerStateInfo.PlayMethodEnum;
    repeatMode?: PlayerStateInfo.RepeatModeEnum;
}
export namespace PlayerStateInfo {
    export type PlayMethodEnum = 'Transcode' | 'DirectStream' | 'DirectPlay';
    export const PlayMethodEnum = {
        Transcode: 'Transcode' as PlayMethodEnum,
        DirectStream: 'DirectStream' as PlayMethodEnum,
        DirectPlay: 'DirectPlay' as PlayMethodEnum
    };
    export type RepeatModeEnum = 'RepeatNone' | 'RepeatAll' | 'RepeatOne';
    export const RepeatModeEnum = {
        RepeatNone: 'RepeatNone' as RepeatModeEnum,
        RepeatAll: 'RepeatAll' as RepeatModeEnum,
        RepeatOne: 'RepeatOne' as RepeatModeEnum
    };
}