/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PlaystateRequest { 
    command?: PlaystateRequest.CommandEnum;
    seekPositionTicks?: number;
    controllingUserId?: string;
}
export namespace PlaystateRequest {
    export type CommandEnum = 'Stop' | 'Pause' | 'Unpause' | 'NextTrack' | 'PreviousTrack' | 'Seek' | 'Rewind' | 'FastForward' | 'PlayPause';
    export const CommandEnum = {
        Stop: 'Stop' as CommandEnum,
        Pause: 'Pause' as CommandEnum,
        Unpause: 'Unpause' as CommandEnum,
        NextTrack: 'NextTrack' as CommandEnum,
        PreviousTrack: 'PreviousTrack' as CommandEnum,
        Seek: 'Seek' as CommandEnum,
        Rewind: 'Rewind' as CommandEnum,
        FastForward: 'FastForward' as CommandEnum,
        PlayPause: 'PlayPause' as CommandEnum
    };
}