/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProvidersSongInfo { 
    albumArtists?: Array<string>;
    album?: string;
    artists?: Array<string>;
    name?: string;
    metadataLanguage?: string;
    metadataCountryCode?: string;
    providerIds?: { [key: string]: string; };
    year?: number;
    indexNumber?: number;
    parentIndexNumber?: number;
    premiereDate?: Date;
    isAutomated?: boolean;
}