/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseItemDto } from './baseItemDto';

export interface RecommendationDto { 
    items?: Array<BaseItemDto>;
    recommendationType?: RecommendationDto.RecommendationTypeEnum;
    baselineItemName?: string;
    categoryId?: number;
}
export namespace RecommendationDto {
    export type RecommendationTypeEnum = 'SimilarToRecentlyPlayed' | 'SimilarToLikedItem' | 'HasDirectorFromRecentlyPlayed' | 'HasActorFromRecentlyPlayed' | 'HasLikedDirector' | 'HasLikedActor';
    export const RecommendationTypeEnum = {
        SimilarToRecentlyPlayed: 'SimilarToRecentlyPlayed' as RecommendationTypeEnum,
        SimilarToLikedItem: 'SimilarToLikedItem' as RecommendationTypeEnum,
        HasDirectorFromRecentlyPlayed: 'HasDirectorFromRecentlyPlayed' as RecommendationTypeEnum,
        HasActorFromRecentlyPlayed: 'HasActorFromRecentlyPlayed' as RecommendationTypeEnum,
        HasLikedDirector: 'HasLikedDirector' as RecommendationTypeEnum,
        HasLikedActor: 'HasLikedActor' as RecommendationTypeEnum
    };
}