/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SearchSearchHint { 
    itemId?: number;
    id?: number;
    name?: string;
    indexNumber?: number;
    productionYear?: number;
    parentIndexNumber?: number;
    primaryImageTag?: string;
    thumbImageTag?: string;
    thumbImageItemId?: string;
    backdropImageTag?: string;
    backdropImageItemId?: string;
    type?: string;
    isFolder?: boolean;
    runTimeTicks?: number;
    mediaType?: string;
    startDate?: Date;
    endDate?: Date;
    series?: string;
    status?: string;
    album?: string;
    albumId?: number;
    albumArtist?: string;
    artists?: Array<string>;
    songCount?: number;
    episodeCount?: number;
    channelName?: string;
    primaryImageAspectRatio?: number;
}