/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SyncModelItemFileInfo { 
    type?: SyncModelItemFileInfo.TypeEnum;
    name?: string;
    path?: string;
    imageType?: SyncModelItemFileInfo.ImageTypeEnum;
    index?: number;
}
export namespace SyncModelItemFileInfo {
    export type TypeEnum = 'Media' | 'Image' | 'Subtitles';
    export const TypeEnum = {
        Media: 'Media' as TypeEnum,
        Image: 'Image' as TypeEnum,
        Subtitles: 'Subtitles' as TypeEnum
    };
    export type ImageTypeEnum = 'Primary' | 'Art' | 'Backdrop' | 'Banner' | 'Logo' | 'Thumb' | 'Disc' | 'Box' | 'Screenshot' | 'Menu' | 'Chapter' | 'BoxRear' | 'Thumbnail';
    export const ImageTypeEnum = {
        Primary: 'Primary' as ImageTypeEnum,
        Art: 'Art' as ImageTypeEnum,
        Backdrop: 'Backdrop' as ImageTypeEnum,
        Banner: 'Banner' as ImageTypeEnum,
        Logo: 'Logo' as ImageTypeEnum,
        Thumb: 'Thumb' as ImageTypeEnum,
        Disc: 'Disc' as ImageTypeEnum,
        Box: 'Box' as ImageTypeEnum,
        Screenshot: 'Screenshot' as ImageTypeEnum,
        Menu: 'Menu' as ImageTypeEnum,
        Chapter: 'Chapter' as ImageTypeEnum,
        BoxRear: 'BoxRear' as ImageTypeEnum,
        Thumbnail: 'Thumbnail' as ImageTypeEnum
    };
}