/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseItemDto } from './baseItemDto';
import { SyncModelItemFileInfo } from './syncModelItemFileInfo';

export interface SyncModelSyncedItem { 
    serverId?: string;
    syncJobId?: number;
    syncJobName?: string;
    syncJobDateCreated?: Date;
    syncJobItemId?: number;
    originalFileName?: string;
    item?: BaseItemDto;
    userId?: string;
    additionalFiles?: Array<SyncModelItemFileInfo>;
}