/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SyncModelSyncJobRequest { 
    targetId?: string;
    itemIds?: Array<string>;
    category?: SyncModelSyncJobRequest.CategoryEnum;
    parentId?: string;
    quality?: string;
    profile?: string;
    container?: string;
    videoCodec?: string;
    audioCodec?: string;
    name?: string;
    userId?: string;
    unwatchedOnly?: boolean;
    syncNewContent?: boolean;
    itemLimit?: number;
    bitrate?: number;
}
export namespace SyncModelSyncJobRequest {
    export type CategoryEnum = 'Latest' | 'NextUp' | 'Resume';
    export const CategoryEnum = {
        Latest: 'Latest' as CategoryEnum,
        NextUp: 'NextUp' as CategoryEnum,
        Resume: 'Resume' as CategoryEnum
    };
}