/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SyncModelSyncProfileOption } from './syncModelSyncProfileOption';
import { SyncModelSyncQualityOption } from './syncModelSyncQualityOption';
import { SyncSyncTarget } from './syncSyncTarget';

export interface SyncModelSyncDialogOptions { 
    targets?: Array<SyncSyncTarget>;
    options?: Array<SyncModelSyncDialogOptions.OptionsEnum>;
    qualityOptions?: Array<SyncModelSyncQualityOption>;
    profileOptions?: Array<SyncModelSyncProfileOption>;
}
export namespace SyncModelSyncDialogOptions {
    export type OptionsEnum = 'Name' | 'Quality' | 'UnwatchedOnly' | 'SyncNewContent' | 'ItemLimit' | 'Profile';
    export const OptionsEnum = {
        Name: 'Name' as OptionsEnum,
        Quality: 'Quality' as OptionsEnum,
        UnwatchedOnly: 'UnwatchedOnly' as OptionsEnum,
        SyncNewContent: 'SyncNewContent' as OptionsEnum,
        ItemLimit: 'ItemLimit' as OptionsEnum,
        Profile: 'Profile' as OptionsEnum
    };
}