/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MediaSourceInfo } from './mediaSourceInfo';
import { SyncModelItemFileInfo } from './syncModelItemFileInfo';

export interface SyncModelSyncJobItem { 
    id?: number;
    jobId?: number;
    itemId?: number;
    itemName?: string;
    mediaSourceId?: string;
    mediaSource?: MediaSourceInfo;
    targetId?: string;
    outputPath?: string;
    status?: SyncModelSyncJobItem.StatusEnum;
    progress?: number;
    dateCreated?: Date;
    primaryImageItemId?: number;
    primaryImageTag?: string;
    temporaryPath?: string;
    additionalFiles?: Array<SyncModelItemFileInfo>;
    itemDateModifiedTicks?: number;
}
export namespace SyncModelSyncJobItem {
    export type StatusEnum = 'Queued' | 'Converting' | 'ReadyToTransfer' | 'Transferring' | 'Synced' | 'Failed';
    export const StatusEnum = {
        Queued: 'Queued' as StatusEnum,
        Converting: 'Converting' as StatusEnum,
        ReadyToTransfer: 'ReadyToTransfer' as StatusEnum,
        Transferring: 'Transferring' as StatusEnum,
        Synced: 'Synced' as StatusEnum,
        Failed: 'Failed' as StatusEnum
    };
}