/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdatesInstallationInfo } from './updatesInstallationInfo';

export interface SystemInfo { 
    systemUpdateLevel?: SystemInfo.SystemUpdateLevelEnum;
    operatingSystemDisplayName?: string;
    packageName?: string;
    hasPendingRestart?: boolean;
    isShuttingDown?: boolean;
    operatingSystem?: string;
    supportsLibraryMonitor?: boolean;
    webSocketPortNumber?: number;
    completedInstallations?: Array<UpdatesInstallationInfo>;
    canSelfRestart?: boolean;
    canSelfUpdate?: boolean;
    canLaunchWebBrowser?: boolean;
    programDataPath?: string;
    itemsByNamePath?: string;
    cachePath?: string;
    logPath?: string;
    internalMetadataPath?: string;
    transcodingTempPath?: string;
    httpServerPortNumber?: number;
    supportsHttps?: boolean;
    httpsPortNumber?: number;
    hasUpdateAvailable?: boolean;
    supportsAutoRunAtStartup?: boolean;
    hardwareAccelerationRequiresPremiere?: boolean;
    localAddress?: string;
    wanAddress?: string;
    serverName?: string;
    version?: string;
    id?: string;
}
export namespace SystemInfo {
    export type SystemUpdateLevelEnum = 'Release' | 'Beta' | 'Dev';
    export const SystemUpdateLevelEnum = {
        Release: 'Release' as SystemUpdateLevelEnum,
        Beta: 'Beta' as SystemUpdateLevelEnum,
        Dev: 'Dev' as SystemUpdateLevelEnum
    };
}