/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TasksTaskResult { 
    startTimeUtc?: Date;
    endTimeUtc?: Date;
    status?: TasksTaskResult.StatusEnum;
    name?: string;
    key?: string;
    id?: string;
    errorMessage?: string;
    longErrorMessage?: string;
}
export namespace TasksTaskResult {
    export type StatusEnum = 'Completed' | 'Failed' | 'Cancelled' | 'Aborted';
    export const StatusEnum = {
        Completed: 'Completed' as StatusEnum,
        Failed: 'Failed' as StatusEnum,
        Cancelled: 'Cancelled' as StatusEnum,
        Aborted: 'Aborted' as StatusEnum
    };
}