/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TasksTaskResult } from './tasksTaskResult';
import { TasksTaskTriggerInfo } from './tasksTaskTriggerInfo';

export interface TasksTaskInfo { 
    name?: string;
    state?: TasksTaskInfo.StateEnum;
    currentProgressPercentage?: number;
    id?: string;
    lastExecutionResult?: TasksTaskResult;
    triggers?: Array<TasksTaskTriggerInfo>;
    description?: string;
    category?: string;
    isHidden?: boolean;
    key?: string;
}
export namespace TasksTaskInfo {
    export type StateEnum = 'Idle' | 'Cancelling' | 'Running';
    export const StateEnum = {
        Idle: 'Idle' as StateEnum,
        Cancelling: 'Cancelling' as StateEnum,
        Running: 'Running' as StateEnum
    };
}