/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TupleDoubleDouble } from './tupleDoubleDouble';

export interface TranscodingInfo { 
    audioCodec?: string;
    videoCodec?: string;
    container?: string;
    isVideoDirect?: boolean;
    isAudioDirect?: boolean;
    bitrate?: number;
    framerate?: number;
    completionPercentage?: number;
    transcodingPositionTicks?: number;
    transcodingStartPositionTicks?: number;
    width?: number;
    height?: number;
    audioChannels?: number;
    transcodeReasons?: Array<TranscodingInfo.TranscodeReasonsEnum>;
    currentCpuUsage?: number;
    averageCpuUsage?: number;
    cpuHistory?: Array<TupleDoubleDouble>;
    currentThrottle?: number;
    videoDecoder?: string;
    videoDecoderIsHardware?: boolean;
    videoDecoderMediaType?: string;
    videoDecoderHwAccel?: string;
    videoEncoder?: string;
    videoEncoderIsHardware?: boolean;
    videoEncoderMediaType?: string;
    videoEncoderHwAccel?: string;
}
export namespace TranscodingInfo {
    export type TranscodeReasonsEnum = 'ContainerNotSupported' | 'VideoCodecNotSupported' | 'AudioCodecNotSupported' | 'ContainerBitrateExceedsLimit' | 'AudioBitrateNotSupported' | 'AudioChannelsNotSupported' | 'VideoResolutionNotSupported' | 'UnknownVideoStreamInfo' | 'UnknownAudioStreamInfo' | 'AudioProfileNotSupported' | 'AudioSampleRateNotSupported' | 'AnamorphicVideoNotSupported' | 'InterlacedVideoNotSupported' | 'SecondaryAudioNotSupported' | 'RefFramesNotSupported' | 'VideoBitDepthNotSupported' | 'VideoBitrateNotSupported' | 'VideoFramerateNotSupported' | 'VideoLevelNotSupported' | 'VideoProfileNotSupported' | 'AudioBitDepthNotSupported' | 'SubtitleCodecNotSupported' | 'DirectPlayError';
    export const TranscodeReasonsEnum = {
        ContainerNotSupported: 'ContainerNotSupported' as TranscodeReasonsEnum,
        VideoCodecNotSupported: 'VideoCodecNotSupported' as TranscodeReasonsEnum,
        AudioCodecNotSupported: 'AudioCodecNotSupported' as TranscodeReasonsEnum,
        ContainerBitrateExceedsLimit: 'ContainerBitrateExceedsLimit' as TranscodeReasonsEnum,
        AudioBitrateNotSupported: 'AudioBitrateNotSupported' as TranscodeReasonsEnum,
        AudioChannelsNotSupported: 'AudioChannelsNotSupported' as TranscodeReasonsEnum,
        VideoResolutionNotSupported: 'VideoResolutionNotSupported' as TranscodeReasonsEnum,
        UnknownVideoStreamInfo: 'UnknownVideoStreamInfo' as TranscodeReasonsEnum,
        UnknownAudioStreamInfo: 'UnknownAudioStreamInfo' as TranscodeReasonsEnum,
        AudioProfileNotSupported: 'AudioProfileNotSupported' as TranscodeReasonsEnum,
        AudioSampleRateNotSupported: 'AudioSampleRateNotSupported' as TranscodeReasonsEnum,
        AnamorphicVideoNotSupported: 'AnamorphicVideoNotSupported' as TranscodeReasonsEnum,
        InterlacedVideoNotSupported: 'InterlacedVideoNotSupported' as TranscodeReasonsEnum,
        SecondaryAudioNotSupported: 'SecondaryAudioNotSupported' as TranscodeReasonsEnum,
        RefFramesNotSupported: 'RefFramesNotSupported' as TranscodeReasonsEnum,
        VideoBitDepthNotSupported: 'VideoBitDepthNotSupported' as TranscodeReasonsEnum,
        VideoBitrateNotSupported: 'VideoBitrateNotSupported' as TranscodeReasonsEnum,
        VideoFramerateNotSupported: 'VideoFramerateNotSupported' as TranscodeReasonsEnum,
        VideoLevelNotSupported: 'VideoLevelNotSupported' as TranscodeReasonsEnum,
        VideoProfileNotSupported: 'VideoProfileNotSupported' as TranscodeReasonsEnum,
        AudioBitDepthNotSupported: 'AudioBitDepthNotSupported' as TranscodeReasonsEnum,
        SubtitleCodecNotSupported: 'SubtitleCodecNotSupported' as TranscodeReasonsEnum,
        DirectPlayError: 'DirectPlayError' as TranscodeReasonsEnum
    };
}