/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdatesPackageVersionInfo } from './updatesPackageVersionInfo';

export interface UpdatesPackageInfo { 
    id?: string;
    name?: string;
    shortDescription?: string;
    overview?: string;
    isPremium?: boolean;
    adult?: boolean;
    richDescUrl?: string;
    thumbImage?: string;
    previewImage?: string;
    type?: string;
    targetFilename?: string;
    owner?: string;
    category?: string;
    tileColor?: string;
    featureId?: string;
    regInfo?: string;
    price?: number;
    targetSystem?: UpdatesPackageInfo.TargetSystemEnum;
    guid?: string;
    totalRatings?: number;
    avgRating?: number;
    isRegistered?: boolean;
    expDate?: Date;
    versions?: Array<UpdatesPackageVersionInfo>;
    enableInAppStore?: boolean;
    installs?: number;
}
export namespace UpdatesPackageInfo {
    export type TargetSystemEnum = 'Server' | 'MBTheater' | 'MBClassic';
    export const TargetSystemEnum = {
        Server: 'Server' as TargetSystemEnum,
        MBTheater: 'MBTheater' as TargetSystemEnum,
        MBClassic: 'MBClassic' as TargetSystemEnum
    };
}