/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdatesInstallationInfo { 
    id?: string;
    name?: string;
    assemblyGuid?: string;
    version?: string;
    updateClass?: UpdatesInstallationInfo.UpdateClassEnum;
    percentComplete?: number;
}
export namespace UpdatesInstallationInfo {
    export type UpdateClassEnum = 'Release' | 'Beta' | 'Dev';
    export const UpdateClassEnum = {
        Release: 'Release' as UpdateClassEnum,
        Beta: 'Beta' as UpdateClassEnum,
        Dev: 'Dev' as UpdateClassEnum
    };
}