/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdatesPackageVersionInfo { 
    name?: string;
    guid?: string;
    versionStr?: string;
    classification?: UpdatesPackageVersionInfo.ClassificationEnum;
    description?: string;
    requiredVersionStr?: string;
    sourceUrl?: string;
    checksum?: string;
    targetFilename?: string;
    infoUrl?: string;
    runtimes?: string;
}
export namespace UpdatesPackageVersionInfo {
    export type ClassificationEnum = 'Release' | 'Beta' | 'Dev';
    export const ClassificationEnum = {
        Release: 'Release' as ClassificationEnum,
        Beta: 'Beta' as ClassificationEnum,
        Dev: 'Dev' as ClassificationEnum
    };
}