/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserItemDataDto { 
    rating?: number;
    playedPercentage?: number;
    unplayedItemCount?: number;
    playbackPositionTicks?: number;
    playCount?: number;
    isFavorite?: boolean;
    likes?: boolean;
    lastPlayedDate?: Date;
    played?: boolean;
    key?: string;
    itemId?: string;
}