/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurationUserConfiguration } from './configurationUserConfiguration';
import { UsersUserPolicy } from './usersUserPolicy';

export interface UserDto { 
    name?: string;
    serverId?: string;
    serverName?: string;
    connectUserName?: string;
    connectLinkType?: UserDto.ConnectLinkTypeEnum;
    id: string;
    primaryImageTag?: string;
    hasPassword?: boolean;
    hasConfiguredPassword?: boolean;
    hasConfiguredEasyPassword?: boolean;
    enableAutoLogin?: boolean;
    lastLoginDate?: Date;
    lastActivityDate?: Date;
    configuration?: ConfigurationUserConfiguration;
    policy?: UsersUserPolicy;
    primaryImageAspectRatio?: number;
}
export namespace UserDto {
    export type ConnectLinkTypeEnum = 'LinkedUser' | 'Guest';
    export const ConnectLinkTypeEnum = {
        LinkedUser: 'LinkedUser' as ConnectLinkTypeEnum,
        Guest: 'Guest' as ConnectLinkTypeEnum
    };
}
