/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UsersForgotPasswordResult { 
    action?: UsersForgotPasswordResult.ActionEnum;
    pinFile?: string;
    pinExpirationDate?: Date;
}
export namespace UsersForgotPasswordResult {
    export type ActionEnum = 'ContactAdmin' | 'PinCode' | 'InNetworkRequired';
    export const ActionEnum = {
        ContactAdmin: 'ContactAdmin' as ActionEnum,
        PinCode: 'PinCode' as ActionEnum,
        InNetworkRequired: 'InNetworkRequired' as ActionEnum
    };
}