/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.4.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UsersUserAction { 
    id?: string;
    serverId?: string;
    userId?: string;
    itemId?: string;
    type?: UsersUserAction.TypeEnum;
    date?: Date;
    positionTicks?: number;
}
export namespace UsersUserAction {
    export type TypeEnum = 'PlayedItem';
    export const TypeEnum = {
        PlayedItem: 'PlayedItem' as TypeEnum
    };
}